spring:
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
